### ISSUE TITLE
Check for credentials in $HOME/.docker/config.json

### ISSUE THREAD

**Issue by dmc5179** [lmzuccarelli/rust-operator-catalog-viewer#1]
I have my pull secret in $HOME/.docker/config.json which is one place oc-mirror, podman, and other tools will check for credentials.
Command fails when pull-secret is not located in $XDG_RUNTIME_DIR/containers/auth.json with

```
 [ ERROR 2024-08-09 18:48:46.652 ]   : Some(
    MirrorError {
        details: "get_credentials Some(\n    Os {\n        code: 2,\n        kind: NotFound,\n        message: \"No such file or directory\",\n    },\n)",
    },
)
```

Check for pull-secret in $HOME/.docker/config.json if not found in $XDG_RUNTIME_DIR/containers/auth.json

**Comment by lmzuccarelli** [comment]
@dmc5179 - Thanks for raising this issue. I have bumped the auth module version, it contains the change to look for &HOME/.docker/config.json if $XDG_RUNTIME_DIR/containers/auth.json is not set or missing
